/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.adamludzia;

import pl.adamludzia.model.CreditOffer;
import pl.adamludzia.service.CreditApplicationParametersProvider;
import pl.adamludzia.service.CreditOffersCalculator;

public class App {

    public static void main(String[] args) {
        var paramsProvider = new CreditApplicationParametersProvider();
        var calculator = new CreditOffersCalculator();

        var params = paramsProvider.getCreditParameters();
        var offers = calculator.getOffers(params);

        int iterator = 1;
        for (CreditOffer offer : offers) {
            System.out.println("- - - - Oferta " + iterator + " - - - -");
            System.out.println("Maksymalna długość okresu kredytowania: " + offer.maxCreditLength());
            System.out.println("Maksymalna wartość kredytu: " + offer.maxCreditAmout());
            System.out.println("Maksymalna miesięczna wysokość raty kredytowej: " + offer.maxMontlyCreditPayment());
            System.out.println("\n\n");
            iterator++;
        }
    }

}
